# Site
name: "The Relational Kitchen"
title: "Relational Kitchen"
description: "Make good food. Grow good plants. Connect."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-137370511-1'
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  pam:
    name: pam
    display_name: Pam
    gravatar: c6c898a16cee018bd81bab63ce48e568
    email: pkn@nielski.com
    web: https://www.instagram.com/messystove/
    twitter: https://www.instagram.com/messystove/
    description: "Pam is the author of this blog."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"
